app:
  name: stage-gpmodel
  cronJobName: stage-gpmodel-cron-job
  label: gpmodel
  namespace: staging
  configMap: env-gp-model-staging
images:
  tag: stage-7b8ed7e5-1709825189
  repositories:
    cronJob: eu.gcr.io/airqo-250220/airqo-stage-gp-model-job
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
  requests:
    cpu: 50m
    memory: 100Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: gp-model-job-config-files
