app:
  name: prod-gpmodel
  cronJobName: prod-gpmodel-cron-job
  brokerConsumerName: prod-gpmodel-broker-consumer
  label: gpmodel
  namespace: production
  configMap: env-gp-model-production
images:
  tag: prod-4b9ff37f-1701901839
  repositories:
    cronJob: eu.gcr.io/airqo-250220/airqo-gp-model-job
    brokerConsumer: eu.gcr.io/airqo-250220/airqo-gp-model-broker-consumer
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
resources:
  limits:
    cpu: 2000m
    memory: 4000Mi
  requests:
    cpu: 50m
    memory: 100Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: gp-model-job-config-files
