app:
  name: stage-device-status-job
  namespace: staging
  configmap: env-device-status-staging
image:
  repository: eu.gcr.io/airqo-250220/airqo-stage-device-status-job
  tag: stage-77cc531a-1707788474
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
