apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: message-broker
spec:
  kafka:
    version: 3.6.0
    replicas: 3
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: "1"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30200
          brokers:
            - broker: 0
              nodePort: 30201
              advertisedHost: $(BROKER0_IP)
            - broker: 1
              nodePort: 30202
              advertisedHost: $(BROKER1_IP)
            - broker: 2
              nodePort: 30203
              advertisedHost: $(BROKER2_IP)
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.6"
      message.max.bytes: 2097152
      replica.fetch.max.bytes: 2097152
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  entityOperator:
    topicOperator: {}
    userOperator: {}
