app:
  name: airqo-exceedance-job
  namespace: production
  configmap: env-exceedance-production
image:
  repository: eu.gcr.io/airqo-250220/airqo-exceedance-job
  tag: prod-df404f12-1713873410
nameOverride: ''
fullnameOverride: ''
