app:
  name: kcca-exceedance-job
  namespace: staging
  configmap: env-exceedance-staging
image:
  repository: eu.gcr.io/airqo-250220/stage-kcca-exceedance-job
  tag: stage-8f344976-1711113910
nameOverride: ''
fullnameOverride: ''
