app:
  name: airqo-exceedance-job
  namespace: production
  configmap: env-exceedance-production
image:
  repository: eu.gcr.io/airqo-250220/airqo-exceedance-job
  tag: prod-f9415d6d-1700115862
nameOverride: ''
fullnameOverride: ''
