app:
  name: kcca-exceedance-job
  namespace: production
  configmap: env-exceedance-production
image:
  repository: eu.gcr.io/airqo-250220/kcca-exceedance-job
  tag: prod-70cadf6b-1698788503
nameOverride: ''
fullnameOverride: ''
