app:
  name: airqo-exceedance-job
  namespace: staging
  configmap: env-exceedance-staging
image:
  repository: eu.gcr.io/airqo-250220/stage-airqo-exceedance-job
  tag: stage-3b77b6fc-1686749518
nameOverride: ''
fullnameOverride: ''
