app:
  name: kcca-exceedance-job
  namespace: production
  configmap: env-exceedance-production
image:
  repository: eu.gcr.io/airqo-250220/kcca-exceedance-job
  tag: prod-98b33798-1689260366
nameOverride: ''
fullnameOverride: ''
