app:
  name: airqo-predict-job
  namespace: production
  configmap: env-predict-job-production
schedule: 0 0 * * *
image:
  repository: eu.gcr.io/airqo-250220/airqo-predict-job
  tag: prod-05283ddd-1686833455
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: predict-job-config-files
