app:
  name: stage-device-uptime-job
  namespace: staging
  configmap: env-device-uptime-staging
image:
  repository: eu.gcr.io/airqo-250220/airqo-stage-device-uptime-job
  tag: stage-57e991d2-1689862096
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: device-uptime-v2-files
