app:
  name: prod-device-uptime-job
  namespace: production
  configmap: env-device-uptime-production
image:
  repository: eu.gcr.io/airqo-250220/airqo-device-uptime-job
  tag: prod-7d14ddf0-1690209418
nameOverride: ''
fullnameOverride: ''
resources:
  limits:
    cpu: 1000m
    memory: 4000Mi
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
volumes:
  - name: config-volume
    configMap:
      name: device-uptime-v2-files
