name: code-coverage-workflow

on: [push, pull_request]

jobs:
  auth-service:
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
        run:
          working-directory: src/auth-service
    name: Code Coverage for authservice
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          node-version: 18

    - name: Install dependencies
      run: 
        npm install

    - name: Run tests and collect coverage
      continue-on-error: true
      run: 
        npm run test
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with: 
        directory: src/auth-service/coverage
        
  device-monitoring:
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: src/device-monitoring
    name: Code Coverage for device-monitoring
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements/prod.txt
    - name: Run tests and collect coverage
      run: pytest --cov=. tests/ --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with: 
        directory: src/device-monitoring

  device-registry:  
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: src/device-registry
    name: Code Coverage for device-registry
    env:
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      REDIS_SERVER: ${{ secrets.REDIS_SERVER }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}   
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          node-version: 18
    
    - name: Install dependencies
      run: 
        npm install
    
    - name: Run tests and collect coverage
      continue-on-error: true
      run: 
        npm run test
            
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with: 
        directory: src/device-registry/coverage
    

        
        
        
        
        
        
        
        
        
