name: code-coverage-workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    defaults:
        run:
          working-directory: src/device-registry
    name: CodeCoverage
    env:
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      REDIS_SERVER: ${{ secrets.REDIS_SERVER }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}      
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          node-version: 18

    - name: Login to GCP
      uses: google-github-actions/auth@v1.1.1
      with:
        credentials_json: ${{ secrets.GCP_SA_CREDENTIALS }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.1

    - name: Install dependencies
      run: 
        npm install

    - name: Run tests and collect coverage
      continue-on-error: true
      run: 
        npm run test
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with: 
        directory: ./coverage/
        
        
        
        
        
        
        
        
        
        